### ISSUE TITLE
FATAL cannot start server: system error when trying to use host directories

### ISSUE THREAD

**Issue by fridaystreet** [arangodb/arangodb-docker#13]
If I try and specify the host directories in my docker-compose.yml I just get the error.

starting ArangoDB in stand-alone mode
creating initial user, please wait ...
2015-10-07T05:11:17Z [15] FATAL cannot start server: system error
More error details may be provided in the logfile '/tmp/arangodb.log'

Without them specified everything runs fine. I'm just using latest.

These are the volume lines from .yml
- ../arangodb/data/database:/var/lib/arangodb:rw
- ../arangodb/data/apps:/var/lib/arangodb-apps:rw
- ../arangodb/data/logs:/var/log/arangodb:rw

I've also tried each line individually too, but no different. I can confirm it is definitely using the directories as files and folders are created. arangodb.log is created in my logs dir, but it's empty.

I've also ran a chown -R 999 on my local /arangodb/data dir

Any assistance would be greatly appreciated.

Cheers
Paul

**Comment by fceller** [comment]
Can you try to use docker directly? Does this work?

```
fceller@chorweiler:~> mkdir /tmp/TESTDIR
fceller@chorweiler:~> sudo chown 999:999 /tmp/TESTDIR
fceller@chorweiler:~> docker run -v /tmp/TESTDIR:/var/lib/arangodb:rw -it arangodb/arangodb:2.6.9 

starting ArangoDB in stand-alone mode
creating initial user, please wait ...
========================================================================
ArangoDB User: "root"
ArangoDB Password: "Nz5kmsGbWuaHldl6"
========================================================================
2015-10-07T11:21:16Z [50] INFO ArangoDB 2.6.9 64bit -- ICU 54.1, V8 4.1.0.27, OpenSSL 1.0.1k 8 Jan 2015
2015-10-07T11:21:16Z [50] INFO using default language 'en'
```

**Comment by fridaystreet** [comment]
Hi fceller, 

Thanks for the quick response, yep that works. Should have thought to try that. Although saying that I also forgot to say that the error was running on osx using docker machine through a vm. I've just tested the above on linux with native docker and it works, so I'll have to try it at home tonight on osx and just make sure it's not just docker machine/osx. If it's still not working then looks like might be something funny going on with docker-compose 

Cheers
Paul

**Comment by fceller** [comment]
@fridaystreet is it working for you? Can we close the issue?

**Comment by fridaystreet** [comment]
Hi Frank,

Sorry for delayed response, I came down with a bit of the flu. Yes that did
work without using Docker compose. Any thoughts on why it wouldn't work
with compose?

Cheers
Paul

**Comment by fceller** [comment]
Hi Paul,

it might have to do with the way docker is implemented on MacOSX. Could you try Docker compose under Linux?

Thanks
  Frank

**Comment by fridaystreet** [comment]
Yep will do. My box at the office is native Linux, I'll give it a try
tomorrow

**Comment by fceller** [comment]
Could you maybe try docker directly on MacOSX? Does this also break?

**Comment by fridaystreet** [comment]
Yep it's working fine with docker direct on osx, sorry that's what I meant
with my original reply. I'd tried it on my mac without compose and it was
ok. I'm pretty sure it failed on linux native on weekend with compose, but
I had a lot on over the weekend and I actually can't recall if that did
work. So I'll try that again tomorrow and report back.

**Comment by mohamnag** [comment]
Hi, I'm having a very similar problem with docker on OSX. I made sure that both `apps/` and `data/` directories exist, are empty and writable by everybody. however I get following log when trying to mount volumes:

```bash
$ docker run --rm -it -p 8529:8529 -v $(pwd)/data/:/var/lib/arangodb/:rw -v $(pwd)/apps/:/var/lib/arangodb-apps/:rw arangodb


2015-11-30T13:58:43Z [1] INFO ArangoDB 2.7.0 [linux] 64bit, using tcmalloc, ICU 54.1, V8 4.3.61, Readline 6.3, OpenSSL 1.0.1k 8 Jan 2015
2015-11-30T13:58:43Z [1] INFO using default language 'en'
2015-11-30T13:58:43Z [1] INFO WAL directory '/var/lib/arangodb/journals' does not exist. creating it...
2015-11-30T13:58:43Z [1] INFO created base application directory '/var/lib/arangodb-apps/_db'
2015-11-30T13:58:43Z [1] INFO loaded database '_system' from '/var/lib/arangodb/databases/database-76906'
2015-11-30T13:58:43Z [1] INFO collection '_users' does not exist, no authentication available
2015-11-30T13:58:43Z [1] INFO using endpoint 'tcp://0.0.0.0:8529' for non-encrypted requests
2015-11-30T13:58:43Z [1] INFO using default API compatibility: 20700
2015-11-30T13:58:43Z [1] INFO JavaScript using startup '/usr/share/arangodb/js', application '/var/lib/arangodb-apps'
2015-11-30T13:58:44Z [1] INFO In database '_system': No version information file found in database directory.
2015-11-30T13:58:44Z [1] INFO In database '_system': Found 24 defined task(s), 19 task(s) to run
2015-11-30T13:58:44Z [1] INFO In database '_system': state prod/standalone/init, tasks setupUsers, createUsersIndex, addDefaultUser, updateUserModel, setupGraphs, createModules, createRouting, createKickstarterConfiguration, insertRedirectionsAll, setupAal, createAalIndex, setupAqlFunctions, createStatistics, createConfiguration, systemAppEndpoints, setupQueues, setupJobs, moveFoxxApps, dropAal
2015-11-30T13:58:45Z [1] ERROR cannot memory map file '/var/lib/arangodb/journals/logfile-142442.db': 'system error'
2015-11-30T13:58:45Z [1] ERROR unable to create logfile '/var/lib/arangodb/journals/logfile-142442.db': system error
2015-11-30T13:58:45Z [1] ERROR unable to create logfile: system error
2015-11-30T13:58:45Z [1] ERROR unable to create new WAL reserve logfile for sized marker: system error
2015-11-30T13:58:45Z [1] WARNING could not save collection create marker in log: system error
2015-11-30T13:58:45Z [1] WARNING could not save attribute marker in log: system error
2015-11-30T13:58:45Z [1] ERROR In database '_system': Executing task #2 (createUsersIndex: create index on 'user' attribute in _users collection) failed with exception: [ArangoError 0: no error] [ArangoError 0: no error]
2015-11-30T13:58:45Z [1] ERROR   at Error (native)
2015-11-30T13:58:45Z [1] ERROR   at ArangoCollection.ensureUniqueConstraint (/usr/share/arangodb/js/server/modules/org/arangodb/arango-collection.js:1138:15)
2015-11-30T13:58:45Z [1] ERROR   at Object.addTask.task (server/upgrade-database.js:559:15)
2015-11-30T13:58:45Z [1] ERROR   at runTasks (server/upgrade-database.js:351:27)
2015-11-30T13:58:45Z [1] ERROR   at upgradeDatabase (server/upgrade-database.js:508:14)
2015-11-30T13:58:45Z [1] ERROR   at upgrade (server/upgrade-database.js:1434:12)
2015-11-30T13:58:45Z [1] ERROR   at server/upgrade-database.js:1443:10
2015-11-30T13:58:45Z [1] ERROR   at server/upgrade-database.js:1444:2
2015-11-30T13:58:45Z [1] ERROR 
2015-11-30T13:58:45Z [1] ERROR In database '_system': Executing task #2 (createUsersIndex: create index on 'user' attribute in _users collection) failed. Aborting init procedure.
2015-11-30T13:58:45Z [1] ERROR In database '_system': Please fix the problem and try starting the server again.
2015-11-30T13:58:45Z [1] FATAL Database '_system' needs upgrade. Please start the server with the --upgrade option
```

I have tried it with both images 2.7.0 and 2.7.1 but all is the same.

**Comment by mohamnag** [comment]
PS: both dirs are owned by 999:999

**Comment by dothebart** [comment]
@mohamnag is this the UID which ArangoDB is running as inside of the container? (see /etc/passwd inside of the docker container)

**Comment by mohamnag** [comment]
@dothebart yes:
```
arangodb:x:999:999:ArangoDB Application User:/usr/share/arangodb:/bin/false
```

**Comment by dothebart** [comment]
will making it world writeable fix the issue? and if yes, which uid then owns the files created?

**Comment by mohamnag** [comment]
dirs were world writable before starting and it did not fix the problem. actually I just tried not to make them world writable and it did not even succeed to create files inside them:
```
2015-11-30T15:54:34Z [1] INFO ArangoDB 2.7.0 [linux] 64bit, using tcmalloc, ICU 54.1, V8 4.3.61, Readline 6.3, OpenSSL 1.0.1k 8 Jan 2015
2015-11-30T15:54:34Z [1] INFO using default language 'en'
2015-11-30T15:54:34Z [1] INFO WAL directory '/var/lib/arangodb/journals' does not exist. creating it...
2015-11-30T15:54:34Z [1] ERROR could not create WAL directory: '/var/lib/arangodb/journals': Protocol error
2015-11-30T15:54:34Z [1] ERROR could not create WAL logfile inventory: system error
2015-11-30T15:54:34Z [1] FATAL unable to start WAL logfile manager
```

when world writable, created files are owned by my user (!= root) and by group 999. Can this be a problem on docker's side? is docker using my user's id inside image?

**Comment by dothebart** [comment]
hm, fancily one has to explicitely mark them as readonly: 
https://docs.docker.com/engine/userguide/dockervolumes/

    $ docker run -d -P --name web -v /opt/webapp:ro training/webapp python app.py

I guess you didn't do that?

**Comment by mohamnag** [comment]
you mean for arrangodb to write on volumes I have to make it readonly?

**Comment by mohamnag** [comment]
ok I think this is a generic docker problem on OSX, just found this: http://stackoverflow.com/questions/26348353/mount-volume-to-docker-image-on-osx

**Comment by dothebart** [comment]
No - ArangoDB has to be able to write to its data volumes for shure. At least with native linux and Docker volumes are writeable by default (as the docker faq stated). I wanted you to find out whether its a problem outside of docker or inside. 

According to that stackoverflow link you found boot2docker has troubles mounting volumes into containers without some reconfiguration?

**Comment by mohamnag** [comment]
not only boot2docker but also the newer docker-machine solution seems to have the same issue when mounting volumes from OSX host into docker images. (I'm actually using latest docker-machine with latest docker).

when I do not explicitly mount volumes from OSX host, the image starts with no problem. This can be because docker is then using auto assigned volumes from inside virtual box image to docker image which are successfully writable (in contrast to volumes mounted from OSX host)

**Comment by dothebart** [comment]
I've added a link to the upstream docker doku, so others hopefully won't trap into this anymore. https://docs.arangodb.com/cookbook/RunningInDockerContainer.html#persistent-data

**Comment by dothebart** [comment]
It seems to be an issue for many non-linux docker users: https://github.com/boot2docker/boot2docker/issues/581 (they even lit a candle for the bugs birthday...)

**Comment by dothebart** [comment]
Ok, Receipe updated to handle Containers in VMs with host OS filesystems.
